name: Publish from tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]*'

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    uses: codenautas/.github/.github/workflows/npm-publish-new-version.yaml@v2
    with:
      node_version: '24'
      skip-tests-until-date: '2000-01-01'
